version: '3'
volumes:
  node_modules:
services:
  nextjs:
    build: .
    ports:
     - "3000:3000"
    environment:
     - NODE_ENV=dev
     - API_BASE_URL=https://api.tvmaze.com
     - PORT=3000
    volumes:
     - .:/app
     - node_modules:/app/node_modules
